version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEBUG=False
      - SECRET_KEY=hocanin_istedigi_guvenli_anahtar
      - DATABASE_URL=postgresql://db_user:db_password@postgres:5432/devdash_db
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: devdash_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
