"""add avatar_img to user

Revision ID: 19296ff4c76f
Revises: 4d3ad2f79f13
Create Date: 2026-05-31 14:24:38.252015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19296ff4c76f'
down_revision = '4d3ad2f79f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_img', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_img')

    # ### end Alembic commands ###
